OUTPUT_ROOT: ASNet_hico
DIST_BACKEND: 'nccl'
WORKERS: 4
DEVICE: cuda
SEED: 42
PI: mAP
CUDNN:
  BENCHMARK: False
  DETERMINISTIC: False
  ENABLED: True
DATASET:
  FILE: hico_det
  NAME: HICODetDataset
  ROOT: 'data/hico/images/test'
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  IMG_NUM_PER_GPU: 2
  SUB_NUM_CLASSES: 1
  OBJ_NUM_CLASSES: 91
  REL_NUM_CLASSES: 117
  MAX_SIZE: 1333
  SCALES: [480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800]
MODEL:
  FILE: asnet
  NAME: ASNet
  RESUME_PATH: 'data/detr-r50-e632da11.pth'
BACKBONE:
  NAME: resnet50
  DIALATION: False
TRANSFORMER:
  BRANCH_AGGREGATION: True
  POSITION_EMBEDDING: sine
  HIDDEN_DIM: 256
  ENC_LAYERS: 6
  DEC_LAYERS: 6
  DIM_FEEDFORWARD: 2048
  DROPOUT: 0.1
  NHEADS: 8
  NUM_QUERIES: 100
  REL_NUM_QUERIES: 16
  PRE_NORM: False
TRAINER:
  FILE: hoi_trainer
  NAME: HOITrainer
TRAIN:
  RESUME: True
TEST:
  REL_ARRAY_PATH: data/hico/rel_np.npy
  USE_EMB: TRUE
  MODE: hico
