OUTPUT_ROOT: ASNet_hoia
DIST_BACKEND: 'nccl'
WORKERS: 4
DEVICE: cuda
SEED: 42
PI: mAP
CUDNN:
  BENCHMARK: False
  DETERMINISTIC: False
  ENABLED: True
DATASET:
  FILE: hico_det
  NAME: HICODetDataset
  ROOT: 'data/hoia/'
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  IMG_NUM_PER_GPU: 2
  SUB_NUM_CLASSES: 1
  OBJ_NUM_CLASSES: 12
  REL_NUM_CLASSES: 10
  MAX_SIZE: 1333
  SCALES: [480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800]
MODEL:
  FILE: hoia_asnet
  NAME: ASNet_HOIA
  RESUME_PATH: 'data/detr-r50-e632da11.pth'
BACKBONE:
  NAME: resnet50
  DIALATION: False
TRANSFORMER:
  BRANCH_AGGREGATION: True
  POSITION_EMBEDDING: sine
  HIDDEN_DIM: 256
  ENC_LAYERS: 6
  DEC_LAYERS: 6
  DIM_FEEDFORWARD: 2048
  DROPOUT: 0.1
  NHEADS: 8
  NUM_QUERIES: 100
  REL_NUM_QUERIES: 16
  PRE_NORM: False
MATCHER:
  COST_CLASS: 1
  COST_BBOX: 5
  COST_GIOU: 2
LOSS: 
  AUX_LOSS: True
  DICE_LOSS_COEF: 1
  REL_CLS_COEF: 1
  DET_CLS_COEF: [1, 1]
  BBOX_LOSS_COEF: [5, 5]
  GIOU_LOSS_COEF: [2, 2]
  EOS_COEF: 0.1
TRAINER:
  FILE: hoi_trainer
  NAME: HOITrainer
TRAIN:
  LR: 0.0001
  LR_BACKBONE: 0.00001
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  LR_DROP: 55
  MAX_EPOCH: 100
  PRINT_FREQ: 20
  SAVE_INTERVAL: 5
  SAVE_EVERY_CHECKPOINT: True
  VAL_WHEN_TRAIN: False
  CLIP_MAX_NORM: 0.1
  RESUME: True
TEST:
  REL_ARRAY_PATH: data/hoia/corre_hoia.npy
  USE_EMB: TRUE
  MODE: hoia
